# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Parser Infrastructure
    App\Core\Parser\ClassDiagram\Infrastructure\Parser\PlantUmlParser:
        public: false

    # Parser Interface binding
    App\Core\Parser\ClassDiagram\Application\Service\ClassDiagramParserInterface:
        alias: App\Core\Parser\ClassDiagram\Infrastructure\Parser\PlantUmlParser

    # Application Services
    App\Core\Parser\ClassDiagram\Application\Service\UmlParserService:
        public: true
        arguments:
            - '@App\Core\Parser\ClassDiagram\Application\Service\ClassDiagramParserInterface'

    # Controllers
    App\Core\Parser\ClassDiagram\Presentation\Controller\:
        resource: '../src/Core/Parser/ClassDiagram/Presentation/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
